version: '3.8'
services:

  ubuntu-sshd:
    image: anti1346/ubuntu2204:sshd
    build:
      context: .
      args:
        SSH_USER: ${SSH_USER}
        SSH_PASSWORD: ${SSH_PASSWORD}
    restart: always
    container_name: ubuntu-sshd
    hostname: ubuntu-sshd
    privileged: true
    environment:
      - SSH_ROOT_PASSWORD=${SSH_ROOT_PASSWORD}
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    ports:
      - 2222:22
    networks:
      - ubuntu_net

networks:
  ubuntu_net:
