version: '3.9'
services:

  ubuntu-systemd:
    build:
      context: .
      dockerfile: Dockerfile
    image: anti1346/ubuntu2204:systemd
    container_name: ubuntu-systemd
    hostname: ubuntu-systemd
    environment:
      - SSH_ROOT_PASSWORD=${SSH_ROOT_PASSWORD}
