version: '3.9'
services:

  ubuntu:
    build:
      context: .
      args:
        SSH_USER: ${SSH_USER}
        SSH_PASSWORD: ${SSH_PASSWORD}
    image: anti1346/ubuntu2204:latest
    container_name: ubuntu
    hostname: ubuntu
