version: '3.8'
services:

  ubuntu-systemd:
    build:
      context: .
      dockerfile: Dockerfile
    image: anti1346/ubuntu2204:systemd
    restart: always
    container_name: ubuntu-systemd
    hostname: ubuntu-systemd
    # privileged: true
    # tty: true
    # stdin_open: true
    # cap_add:
    #   - SYS_ADMIN
    environment:
      - SSH_ROOT_PASSWORD=${SSH_ROOT_PASSWORD}
    volumes:
      - /usr/share/zoneinfo/Asia/Seoul:/etc/localtime:ro
    networks:
      - my_network

networks:
  my_network:
    name: my_network
