version: '3.9'
services:

  ubuntu-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: anti1346/ubuntu2204:proxy
    container_name: ubuntu-proxy
    hostname: ubuntu-proxy
    environment:
      - SSH_ROOT_PASSWORD=${SSH_ROOT_PASSWORD}
