version: '3.9'
services:

  ubuntu-proxy:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    image: anti1346/ubuntu2204:proxy
    container_name: ubuntu-proxy
    hostname: ubuntu-proxy
    volumes:
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./conf/squid.conf:/etc/squid/squid.conf
    ports:
      - 8080:3128
