version: '3.9'
services:

  squid:
    image: ubuntu/squid:latest
    restart: unless-stopped
    container_name: squid
    hostname: squid
    volumes:
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./conf/allowed_ips.txt:/etc/squid/allowed_ips.txt
      - ./conf/allowed_domains.txt:/etc/squid/allowed_domains.txt
      - ./data:/var/spool/squid
      - ./log:/var/log/squid
    ports:
      - 8080:3128
