version: '3.9'
services:
  squid-proxy:
    image: anti1346/ubuntu2204:proxy
    restart: always
    container_name: squid-proxy
    hostname: squid-proxy
    volumes:
      - ./conf/squid.conf:/etc/squid/squid.conf
      - ./conf/allowed_ips.txt:/etc/squid/allowed_ips.txt
      - ./conf/allowed_domains.txt:/etc/squid/allowed_domains.txt
    ports:
      - 8080:3128
