version: "3.8"

services:
  vault-server-1:
    image: vault:latest
    container_name: vault-server-1
    hostname: vault-server-1
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=vault-plaintext-root-token
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"

  vault-server-2:
    image: vault:latest
    container_name: vault-server-2
    hostname: vault-server-2
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=vault-plaintext-root-token
    cap_add:
      - IPC_LOCK
    ports:
      - "8201:8200"

  vault-server-3:
    image: vault:latest
    container_name: vault-server-3
    hostname: vault-server-3
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=vault-plaintext-root-token
    cap_add:
      - IPC_LOCK
    ports:
      - "8202:8200"
